
set(FILES
    Source/O3deFramework_MiscModuleInterface.cpp
    Source/O3deFramework_MiscModuleInterface.h
    Source/O3deFramework_MiscSystemComponentBase.cpp
    Source/O3deFramework_MiscSystemComponentBase.h
    Source/O3deFramework_MiscSystemComponent.cpp
    Source/O3deFramework_MiscSystemComponent.h
    Source/Components/NetConnectionEntitySpawnerComponent.h
    Source/Components/NetConnectionEntitySpawnerComponent.cpp
    Source/NetConnectionEntityBus.cpp
    Source/LevelGameEntitySystemComponent.h
    Source/LevelGameEntitySystemComponent.cpp
    Source/Components/EntityControlComponent.h
    Source/Components/EntityControlComponent.cpp
    Source/SettingsRegistryAccessors.cpp
    Source/Components/PlayerEntityManagerComponent.h
    Source/Components/PlayerEntityManagerComponent.cpp
)
